all:
	pdflatex sprawozdanie

.PHONY: clean
clean:
	rm -f sprawozdanie.out
	rm -f sprawozdanie.aux
	rm -f sprawozdanie.bbl
	rm -f sprawozdanie.blg
	rm -f sprawozdanie.fls
	rm -f sprawozdanie.log
	rm -f sprawozdanie.out
	rm -f sprawozdanie.toc
	rm -f sprawozdanie.dvi
	rm -f sprawozdanie.synctex.gz
	rm -f sprawozdanie.fdb_latexmk
